// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1:string):Promise<string>;

export function Delete(arg1:string):Promise<string>;

export function Update(arg1:string):Promise<string>;
